#!/usr/bin/env python3
"""Generate a compact, deterministic Archie point cloud for ESP32-P4.

The source artwork is intentionally not embedded in firmware. This tool reads
the supplied reference PNG, removes isolated background stars, and emits a
small C++ vertex array that can be animated at runtime without large bitmaps.
"""

from __future__ import annotations

import argparse
import hashlib
import math
import random
from pathlib import Path

from PIL import Image, ImageFilter


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--points", type=int, default=2200)
    parser.add_argument("--crop", default="105,48,545,558")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    crop = tuple(int(part) for part in args.crop.split(","))
    if len(crop) != 4:
        raise SystemExit("--crop must be left,top,right,bottom")

    image = Image.open(args.source).convert("RGB").crop(crop)
    width, height = image.size
    luminance = image.convert("L")

    # Dense character particles survive this neighborhood-density mask while
    # the sparse star field and UI scanlines fall away.
    bright = luminance.point(lambda value: 255 if value >= 72 else 0)
    density = bright.filter(ImageFilter.GaussianBlur(radius=2.2))
    pixels = image.load()
    lum = luminance.load()
    den = density.load()

    candidates: list[tuple[int, int, int, float]] = []
    for y in range(height):
        for x in range(width):
            value = lum[x, y]
            if value < 66:
                continue
            # The staff is a narrow structure; retain it with a slightly lower
            # density threshold than the armor and cloak.
            in_staff = x >= int(width * 0.70)
            threshold = 9 if in_staff else 15
            if den[x, y] < threshold:
                continue
            red, green, blue = pixels[x, y]
            warmth = max(0, red - blue) + max(0, green - blue) * 0.5
            weight = 1.0 + value / 255.0 + warmth / 255.0
            candidates.append((x, y, value, weight))

    if len(candidates) < args.points:
        raise SystemExit(f"only {len(candidates)} candidate pixels for {args.points} points")

    digest = hashlib.sha256(args.source.read_bytes()).digest()
    rng = random.Random(int.from_bytes(digest[:8], "little"))

    # Weighted sampling without replacement. Dense bright points define the
    # silhouette, while dim points keep the granular point-cloud texture.
    keyed: list[tuple[float, tuple[int, int, int, float]]] = []
    for candidate in candidates:
        key = rng.random() ** (1.0 / candidate[3])
        keyed.append((key, candidate))
    selected = [item for _, item in sorted(keyed, reverse=True)[: args.points]]
    selected.sort(key=lambda item: (item[1], item[0]))

    points: list[tuple[int, int, int, int]] = []
    for index, (x, y, value, _) in enumerate(selected):
        # Normalize into a model-space box. The renderer controls final scale.
        nx = round(((x / max(1, width - 1)) - 0.5) * 1024)
        ny = round(((y / max(1, height - 1)) - 0.5) * 1024)
        # A deterministic shallow Z volume gives the 2D reference a subtle
        # parallax rotation without distorting Archie's recognizable outline.
        phase = (x * 73 + y * 151 + index * 19) & 0xFF
        nz = round(math.sin(phase * math.tau / 256.0) * 74)
        glow = max(24, min(255, round(value * 1.18)))
        points.append((nx, ny, nz, glow))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "// Generated by tools/generate_archie_pointcloud.py.",
        "// Source artwork is not embedded; these are quantized particle vertices.",
        "struct ArchiePointVertex {",
        "    int16_t x;",
        "    int16_t y;",
        "    int16_t z;",
        "    uint8_t glow;",
        "};",
        "",
        "inline constexpr ArchiePointVertex kArchiePointVertices[] = {",
    ]
    lines.extend(f"    {{{x}, {y}, {z}, {glow}}}," for x, y, z, glow in points)
    lines.extend(
        [
            "};",
            "",
            "inline constexpr std::size_t kArchiePointVertexCount =",
            "    sizeof(kArchiePointVertices) / sizeof(kArchiePointVertices[0]);",
            "",
        ]
    )
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(points)} vertices to {args.output}")


if __name__ == "__main__":
    main()
